In [1]:
import os 
from langchain_ollama import OllamaLLM
llm = OllamaLLM(model="gemma3:12b")

os.environ['SERPAPI_API_KEY'] = '4d11a637c3f2555f052411f12131ee7cbe8025b6aa47a898c9ba9922a2e55811'

c:\Users\Bistelligence\AppData\Local\pypoetry\Cache\virtualenvs\ollama-app-PvdVXOUT-py3.11\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
from langchain_community.utilities import SerpAPIWrapper

params = {
    "engine" : "google_news", 
    "gl": "KR",
    "hl": "ko",
}
search = SerpAPIWrapper(params=params)

search.run("비스텔리젼스")

[{'position': 1,
  'title': '[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다',
  'source': {'name': '디일렉',
   'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.thelec.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.thelec.kr/news/articleView.html?idxno=33104',
  'thumbnail': 'https://cdn.thelec.kr/news/photo/202502/33104_31164_1118.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNTRWMFprUVdwVFNsbHdURkJsVFJDcUJCaXFCQ2dLTWdheFk1WlFLUWc',
  'date': '02/19/2025, 08:00 AM, +0000 UTC',
  'iso_date': '2025-02-19T08:00:00Z'},
 {'position': 2,
  'title': "비스텔리젼스, '제조 AI' 전용 데이터 가공 솔루션 출시",
  'source': {'name': '디일렉',
   'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.thelec.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.thelec.kr/news/articleView.html?idxno=32943',
  'thumbnail': 'https://cdn.thelec.kr/news/photo/202502/32943_31047_1131.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNVdjMGhrZERWVVRtSklRbmw1VFJEb0FoallCQ2dLTWdhUmNwQW9zZ1k',
  'date': '02/13/2025, 08:00 AM, +0000 UTC',
  'iso_date': '2025-02-13T08:00:00Z'},
 {'position': 3,
  'title': "이한주 비스텔리젼스 대표 “'비스텔리젼스 에지 IoT 플랫폼'으로 산업계 DX 뒷받침”",
  'source': {'name': '전자신문',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.etnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.etnews.com/20230317000043',
  'thumbnail': 'https://img.etnews.com/photonews/2303/1631577_20230320171524_491_0001.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNTBRak5NTlRJeWRVWnFSVVphVFJDc0F4ak1CU2dLTWdZbGhvN3RNUWM',
  'date': '03/17/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-03-17T07:00:00Z'},
 {'position': 4,
  'title': '[신년사] 비스텔리젼스 "산업 데이터분석 신규 솔루션 선보인다"',
  'source': {'name': 'AI타임스',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.aitimes.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.aitimes.com/news/articleView.html?idxno=156937',
  'thumbnail': 'https://cdn.aitimes.com/news/photo/202402/156937_168483_234.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNDRaRWc1VWxkU2MyazVUR2xMVFJDcUJCaXFCQ2dLTWdZVkE0NHJFUXM',
  'date': '02/02/2024, 08:00 AM, +0000 UTC',
  'iso_date': '2024-02-02T08:00:00Z'},
 {'position': 5,
  'title': '한국 제조AI의 개척자 “테크 유행어에 겁먹지 말라”',
  'source': {'name': '포춘코리아 디지털 뉴스',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.fortunekorea.co.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.fortunekorea.co.kr/news/articleView.html?idxno=28468',
  'thumbnail': 'https://www.fortunekorea.co.kr/news/photo/202306/28468_19879_1917.png',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNVFVVFJXTlhsQ1NtdHRNbUo2VFJDSEF4allCQ2dLTWdZQk1JaU1IQWs',
  'date': '06/25/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-06-25T07:00:00Z'},
 {'position': 6,
  'title': '미라콤아이앤씨, 비스텔리젼스와 스마트팩토리·MES 솔루션 사업 협력을 위한 업무협약',
  'source': {'name': '인더스트리뉴스',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.industrynews.co.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.industrynews.co.kr/news/articleView.html?idxno=50969',
  'thumbnail': 'https://cdn.industrynews.co.kr/news/photo/202309/50969_55751_88.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNHROMFF5VFZWV2FFZG1XbEZHVFJEQ0F4allCQ2dLTWdZQllKUjNOQWc',
  'date': '09/13/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-09-13T07:00:00Z'},
 {'position': 7,
  'title': '미라콤아이앤씨, 비스텔리젼스와 AI·빅데이터 기반 스마트팩토리 신사업 ‘맞손’',
  'source': {'name': 'IT비즈뉴스',
   'icon': 'https://encrypted-tbn1.gstatic.com/faviconV2?url=https://www.itbiznews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.itbiznews.com/news/articleView.html?idxno=110854',
  'thumbnail': 'https://cdn.itbiznews.com/news/photo/202309/110854_106977_3723.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNU9abTQ0VldGbVNrazFRazA0VFJEZ0F4aUFCU2dLTWdZaEJKS3NLUWc',
  'date': '09/14/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-09-14T07:00:00Z'},
 {'position': 8,
  'title': '티라유텍-비스텔리젼스, 스마트 제조 엔지니어링 확산 업무협약',
  'source': {'name': '더구루',
   'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.theguru.co.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.theguru.co.kr/news/article.html?no=30831',
  'thumbnail': 'https://www.theguru.co.kr/data/photos/20220104/art_16432427486192_2369bd.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNWtkVTQzU21OdGVqaGhSVEF4VFJEZkF4aUFCU2dLTWdZZGRJeU9zUVk',
  'date': '01/27/2022, 08:00 AM, +0000 UTC',
  'iso_date': '2022-01-27T08:00:00Z'},
 {'position': 9,
  'title': '[AW2023] 인공지능(AI) 품어, 지능형 제조 설비 시스템 구축',
  'source': {'name': '산업종합저널',
   'icon': 'https://encrypted-tbn1.gstatic.com/faviconV2?url=https://industryjournal.co.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://industryjournal.co.kr/news/231642',
  'thumbnail': 'http://img.industryjournal.co.kr/kidd/photo/2023/03/10/1678440056_36.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNXpUMFpmZDBGdGRrUlBha3hhVFJERUF4aW1CU2dLTWdZVkVJZ051UVE',
  'date': '03/10/2023, 08:00 AM, +0000 UTC',
  'iso_date': '2023-03-10T08:00:00Z'},
 {'position': 10,
  'title': '美 시놉시스, 국내 스마트팩토리 솔루션社 비스텔 인수',
  'source': {'name': '한국경제',
   'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.hankyung.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.hankyung.com/article/202106241290i',
  'thumbnail': 'https://img.hankyung.com/photo/202106/01.26733200.1.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iL0NnNDNXWGhsT1dSTlJUVXRTMGR1VFJETkFoajBBeWdLTWdrQmdJcEpNcWpRY0FF',
  'date': '06/24/2021, 07:00 AM, +0000 UTC',
  'iso_date': '2021-06-24T07:00:00Z'},
 {'position': 11,
  'title': '매일 만나는 첨단 산업, 경제, IT 소식',
  'source': {'name': '헬로티',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.hellot.net&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.hellot.net/news/article_print.html?no=75904',
  'thumbnail': 'https://www.hellot.net/data/photos/20230310/art_16783689176689_5e77ae.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iL0NnNUJZbHBFT1dwV2RrVlJRbTVNVFJEVEF4aVFCU2dLTWdrQlVJaEN4ZVFsVkFF',
  'date': '04/03/2023, 03:29 PM, +0000 UTC',
  'iso_date': '2023-04-03T15:29:17Z'},
 {'position': 12,
  'title': 'AI·빅데이터 분석기반 스마트팩토리·MES솔루션 사업 맞손',
  'source': {'name': '정보통신신문',
   'icon': 'https://encrypted-tbn2.gstatic.com/faviconV2?url=https://www.koit.co.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.koit.co.kr/news/articleView.html?idxno=116733',
  'thumbnail': 'https://cdn.koit.co.kr/news/photo/202309/116733_69662_816.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNXBTMk5oVVd0UFR5MDJTWEo1VFJEZ0F4aUFCU2dLTWdZQllKWjNOQWc',
  'date': '09/13/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-09-13T07:00:00Z'},
 {'position': 13,
  'title': '비스텔리젼스, 아산시 스마트 상수도 관리시스템 구축 완료',
  'source': {'name': '전자신문',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.etnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.etnews.com/20220418000060',
  'thumbnail': 'https://img.etnews.com/photonews/2204/1522434_20220418145030_561_0001.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iL0NnNXVRVjg1YTNJMk1sbHZVemh5VFJDRkF4aVZCaWdLTWdrUklZcnJtZW90RXdF',
  'date': '04/18/2022, 07:00 AM, +0000 UTC',
  'iso_date': '2022-04-18T07:00:00Z'},
 {'position': 14,
  'title': "비스텔리젼스, '엔지니어 작업 노하우 관리' 솔루션 연구개발과제 공개",
  'source': {'name': '디일렉',
   'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.thelec.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.thelec.kr/news/articleView.html?idxno=27608',
  'thumbnail': 'https://cdn.thelec.kr/news/photo/202405/27608_25694_3713.png',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iI0NnNTFabk4wZUVFeE9VUXRZVmh3VFJDTUFSaVFBeWdLTWdB',
  'date': '05/03/2024, 07:00 AM, +0000 UTC',
  'iso_date': '2024-05-03T07:00:00Z'},
 {'position': 15,
  'title': '티라유텍, 직교로봇 제조 전문기업 ‘현준에프에이’ 경영권 양수',
  'source': {'name': '인더스트리뉴스',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.industrynews.co.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.industrynews.co.kr/news/articleView.html?idxno=49802',
  'thumbnail': 'https://cdn.industrynews.co.kr/news/photo/202305/49802_53699_4413.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iL0NnNURjbGRqYlROVWRFc3dNMGxxVFJDUUF4allCQ2dLTWdrQmNJSmlQbWM5VWdF',
  'date': '05/15/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-05-15T07:00:00Z'},
 {'position': 16,
  'title': '비스텔리젼스, 신사업부 통해 제조 AI에 집중...분사 후 도약 기반 마련',
  'source': {'name': '전자신문',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.etnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.etnews.com/20211123000126',
  'thumbnail': 'https://img.etnews.com/photonews/2111/1476972_20211124113327_386_0001.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNTJaM2w1YWpseU5qbG5jMmhqVFJESEFoanRCaWdLTWdhTjRvSXB6UU0',
  'date': '11/23/2021, 08:00 AM, +0000 UTC',
  'iso_date': '2021-11-23T08:00:00Z'},
 {'position': 17,
  'title': '비스텔리젼스, 미라콤아이앤씨와 업무협약 체결',
  'source': {'name': '디일렉',
   'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.thelec.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL',
   'authors': ['이민조', '예조기자학교']},
  'link': 'https://www.thelec.kr/news/articleView.html?idxno=23051',
  'thumbnail': 'https://cdn.thelec.kr/news/photo/202309/23051_20489_09.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNDFaVk00TFROaFJUUkZiazh3VFJEQ0F4allCQ2dLTWdZaEJKS3NxUWM',
  'date': '09/14/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-09-14T07:00:00Z'},
 {'position': 18,
  'title': '비스텔리젼스-미라콤아이앤씨, AI·빅데이터 기반 스마트팩토리 사업 협력',
  'source': {'name': '전자신문',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.etnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.etnews.com/20230915000026',
  'thumbnail': 'https://img.etnews.com/news/article/2023/09/15/news-p.v1.20230915.8b0498aec7bb4cbea684e61482067f3a_P1.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNUVlR1ZwWlZJM09HUlJURWhyVFJEQ0FSaURBaWdCTWdZaEJKS3NLUWc',
  'date': '09/15/2023, 07:00 AM, +0000 UTC',
  'iso_date': '2023-09-15T07:00:00Z'},
 {'position': 19,
  'title': '비스텔리젼스, 오리엔트정공과 공정 스마트 이노베이션을 위한 양해각서 체결',
  'source': {'name': '전자신문',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.etnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.etnews.com/20220701000078',
  'thumbnail': 'https://img.etnews.com/photonews/2207/1547756_20220701110142_080_0001.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNDJXR2hLY1VGZlVFaEdaWGxUVFJERUF4aW1CU2dLTWdZZFZKS0xKUWc',
  'date': '07/01/2022, 07:00 AM, +0000 UTC',
  'iso_date': '2022-07-01T07:00:00Z'},
 {'position': 20,
  'title': "비스텔리젼스, 국토부 공모 '스마트시티 인프라 AIoT 핵심기술 개발사업' 참여",
  'source': {'name': '전자신문',
   'icon': 'https://encrypted-tbn0.gstatic.com/faviconV2?url=https://www.etnews.com&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
  'link': 'https://www.etnews.com/20221207000075',
  'thumbnail': 'https://img.etnews.com/photonews/2212/1600855_20221207104131_263_0001.jpg',
  'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNXZUM2QyTmxORFgxcFFXRXRVVFJEWkJCai1BeWdLTWdhVkE0VFBqUWM',
  'date': '12/07/2022, 08:00 AM, +0000 UTC',
  'iso_date': '2022-12-07T08:00:00Z'}]

In [14]:
results = search.run("비스텔리젼스")
len(results)

20

In [15]:
results[0]

{'position': 1,
 'title': '[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다',
 'source': {'name': '디일렉',
  'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.thelec.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
 'link': 'https://www.thelec.kr/news/articleView.html?idxno=33104',
 'thumbnail': 'https://cdn.thelec.kr/news/photo/202502/33104_31164_1118.jpg',
 'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNTRWMFprUVdwVFNsbHdURkJsVFJDcUJCaXFCQ2dLTWdheFk1WlFLUWc',
 'date': '02/19/2025, 08:00 AM, +0000 UTC',
 'iso_date': '2025-02-19T08:00:00Z'}

In [16]:
results[0].keys()

dict_keys(['position', 'title', 'source', 'link', 'thumbnail', 'thumbnail_small', 'date', 'iso_date'])

In [17]:
url = results[0]['link']
url

'https://www.thelec.kr/news/articleView.html?idxno=33104'

In [19]:
from langchain_community.document_loaders import WebBaseLoader

loader = WebBaseLoader(url)
docs = loader.load()

docs[0]

USER_AGENT environment variable not set, consider setting it to identify your requests.

Document(metadata={'source': 'https://www.thelec.kr/news/articleView.html?idxno=33104', 'title': '[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다 < Y인사이트 < 기사본문 - 디일렉(THE ELEC)', 'description': '비스텔리젼스는 산업에 필요한 인공지능(AI) 기술과 데이터 분석을 통해 \u200b제조 산업의 지능화를 이끄는 기업이다.이한주 대표가 반도체와 디스플레이 업계에서 장비 데', 'language': 'ko'}, page_content='\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다 < Y인사이트 < 기사본문 - 디일렉(THE ELEC)\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n주요서비스 바로가기\n본문 바로가기\n매체정보 바로가기\n로그인 바로가기\n기사검색 바로가기\n\n\n\n\n\n\n\n\n\n\n\n\n로그인\n회원가입\n모바일웹\n\n\n\nUPDATE: 2026-01-13 15:37 (화) \n\nENGLISH\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n기사검색\n\n\n\n\n\n\n\n\n\n최신뉴스\n\n\n동정\n\n\n전자엔지니어\n\n\n컨콜전문\n\n\n오피니언\n\n\n\n\n반도체\n\n\n디스플레이\n\n\n배터리\n\n\n방산‧에너지\n\n\n완성품\n\n\n금융\n\n\nIT‧게임\n\n\n통신\n\n\n\n\n중국산업동향\n\n\n반도체\n\n\n디스플레이\n\n\n배터리ㆍ소재부품\n\n\nIT 일반 기타\n\n\n\n\n오피니언\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n이전 기사보기\n다음 기사보기\n\n\n\n\n[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다\n\n\n\n\n\n\n\n\n\n\n글자크기 설정\n\n\n\n\n가\n\n\n\n\n\n\n\n가\n\n기사의 본문 내용은 이 글자크기로 변경됩니다.\n\n\n\n\n\n\n\n\n\n\n스크롤 이동 상태바\n\n\n\n\n\n\n\n\n\nY인사이트\n\n\n[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다\n엣지 플랫폼 기술로 고속 · 대용량 데이터 수집...후공정 이상 감지 솔루션 개발\n\n\n\n\n\r\n\t\t\t\t\t신일범 프로\t\t\t\t\n입력 2025.02.19 11:59\n댓글 1 \n\n\n\n\n\n\n\n\n\n\n\n글자크기 설정\n\n\n\n\n가\n\n\n\n\n\n\n\n가\n\n기사의 본문 내용은 이 글자크기로 변경됩니다.\n\n\n\n\n\n\n\n\n이 기사를 공유합니다\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n이한주 비스텔리젼스 대표[사진=정일규 프로]\n\n\n\n\n\n\n\n\n\n\n비스텔리젼스는 산업에 필요한 인공지능(AI) 기술과 데이터 분석을 통해 \u200b제조 산업의 지능화를 이끄는 기업이다.\n이한주 대표가 반도체와\xa0디스플레이 업계에서 장비 데이터 관리 솔루션으로 잘 알려진 비스텔이 2021년 시놉시스(Synopsys)에 매각한\xa0후\xa0\'비스텔리젼스\'라는 이름으로 새출발했다.\n비스텔리젼스는 반도체 후공정 및 퍼실리티 · 유틸리티 설비처럼 상대적으로 자동화 수준이 낮은 영역을 중심으로 사업을 확장하고 있다. 전공정에서는 이미 FDC(Fault Detection and Classification)와 같은 이상 감지 시스템이 필수적으로 자리 잡았지만, 후공정은 여전히 제한적인 데이터만으로 운영되는 경우가 많다.\n이 대표는 “후공정에서 장비에서 제공하는 데이터만으로는 한계가 있다”며 “엣지 플랫폼 기술을 활용해 직접 고속 · 대용량 데이터를 수집해 FDC와 연계하는 솔루션을 개발했다”고 설명했다.\n비스텔리젼스는 국내 주요\xa0반도체 패키징 · 테스트 전문업체(OSAT)와 협력해 와이어본더, 백그라인더, 다이 어태치 등 후공정 장비에서 초당 수천~수만 건에 이르는 고속 데이터를 수집해 이상 감지 및 품질 관리를 실행해주는 시스템을 성공적으로 구축했다.\n이 대표는 “기존에는 장비가 1초에 한 번씩만 데이터를 보내면, 그 안에서 발생한 이상은 놓칠 수밖에 없었지만, 비스텔리젼스는 초당 수천 건의 데이터를 직접 수집해 실시간 감지한다”며 “이를 통해 품질을 강화할 수 있었고, 고객사에서도 플립칩 등 어드밴스드 패키징에도 확대 적용해야 한다는 피드백을 받았다”고 밝혔다.\n비스텔리젼스는 장비 예지보전과\xa0건강 상태 모니터링을 위한 APM(Asset Performance Management) 솔루션도 준비하고 있다. 비지도 학습 기반 AI 모델로 초기 정상 상태를 학습해 변화를 감지하는 방식이다. 이 대표는 “고장이 잘 발생하지 않는 최신 장비의 경우, 과거 고장 이력을 학습하는 지도학습 방식은 어려움이 있다”면서 “비지도 학습은 초기 상태를 정상으로 설정하고, 변화가 생기면 이를 감지해 모델이 점점 최적화된다”고 설명했다.\n비스텔리젼스는 최근 생성형 AI, 대규모 언어모델(LLM) 기술을 접목해 하이퍼오토메이션(Hyperautomation)을 실현하려는 비전도 제시했다. 엔지니어의 의사결정을 보조하는 버추얼 엔지니어의 개념이다. 이 대표는 “반도체 현장의 작업자는 자동화를 통해 환경이 좋아졌지만, 엔지니어들의 워크 앤 라이프 밸런스는 오히려 악화됐다”며 “AI 에이전트를 활용해 엔지니어들의 반복 작업을 줄이고, 빠르고 정확하게 의사결정하도록 지원하는 방향으로 갈 계획”이라고 밝혔다.\n비스텔리젼스는 올해를 손익분기점 달성의 해로 삼았다. 이 대표는 “올해부터 BEP 달성을 시작으로, 점차 수익을 늘려가서, 2028년에는 상장할 수 있도록 준비할 계획”이라는 청사진을 제시했다.\n비스텔리젼스 이한주 대표를 만나 회사의 기술력과 솔루션, 미래 비전에 관해 들어봤다.\n- 이한주 대표님, 비스텔리젼스라고 하면 과거에 있었던 비스텔이라는 회사를 떠올리시는 분들이 많고, 또 그간의 과정들을 잘 모르시는 분들은 다소 혼동하실 수도 있을 것 같은데요. 소개를 부탁드리겠습니다. 비스텔이라는 회사와 비스텔리젼스는 어떻게 다른지, 그리고 그 과정이 어떻게 흘러왔는지 설명해 주시면 좋겠습니다.\n“말씀하신 대로 특히 반도체나 디스플레이 산업 쪽에서는 비스텔이라는 이름으로 기억하고 계시는 고객들이 상당히 많을 것으로 생각합니다. 저희는 2000년도에 비스텔이라는 회사로 시작을 해서, 반도체와 디스플레이 분야의 전 세계 주요 고객사들을 대상으로 이큅먼트 엔지니어링 솔루션(Equipment Engineering Solution)을 공급하던 회사였습니다.\n이후에 그 제품들이 시놉시스(Synopsys)라는 EDA(Electronic Design Automation) 전문 업체의 설계 및 Fab 데이터와 서로 시너지를 낼 수 있겠다는 생각으로 비스텔이 시놉시스에 합병되는 과정을 거쳤습니다. 2021년 9월에 최종적으로 합병이 마무리됐습니다.\n그 후, 저희는 다시 비스텔리젼스라는 이름으로 재창업을 하게 됐고, 당시 저희가 공급했던 솔루션에 대한 서비스는 저희가 전담해서 제공하는 형태로 사업을 시작했습니다. 이후 지속적인 성장을 위해, 다른 산업으로도 확장하거나 새로운 솔루션들을 개발하고, 또 고객들을 발굴해 나가는 과정을 계속해오고 있습니다.\n저희는 비스텔 시절부터 쌓아온 20여 년간의 경험을 바탕으로, 반도체나 디스플레이처럼 고도화된 자동화 생산 팹(Fab)을 운영하는 환경의 기술들을 다른 산업에도 확산시키자는 큰 목표를 갖고 있습니다. 결국, 우리나라 전체 제조업의 경쟁력을 높여보자는 취지로 다시 시작하게 됐다고 보시면 됩니다.\n반도체, 디스플레이 분야에서도 여전히 후공정 조립 · 테스트 라인이나, 퍼실리티 · 유틸리티 설비와 같은 부분은 전공정 팹에 비해 시스템적으로나 디지털화 수준이 상대적으로 낙후돼 있는 경우가 많습니다. 그래서 저희는 이런 부분들을 전공정 수준의 자동화 수준까지 끌어올려 보자는 목표로, 새로운 솔루션을 계속 개발하고 발굴해서, 고객사에 맞춤형 서비스를 제공하는 사업을 이어가고 있습니다.”\n- 2021년 시놉시스와의 합병 뉴스를 보고 쇼킹하다는 느낌을 받은 기억이 나는데요, 합병 후에 서비스 사업을 떼어 나와서 차린 회사가 비스텔리젼스라는 것이죠?\n“서비스 사업도 있지만, 맨 처음 비스텔을 시작할 때, 사실 몇 가지 다른 제품들을 가지고 있었는데 그 제품들은 시놉시스의 비즈니스와는 시너지 면에서 결이 조금 다른 부분이었습니다. 그래서 그 부분은 저희가 다시 가져와서 계속 발전시켜 나가고 있고, 그 영역에 대한 사업은 초기부터 지금까지 서비스 사업과 함께 계속 진행해오고 있는 상황입니다.”\n- 예전 비스텔에서 반도체나 디스플레이 제조 회사에 공급했던 솔루션은 어떤 것이었어요?\n“주로 장비에서 발생하는 데이터를 기반으로 이상을 감지하거나 품질을 높이기 위해 레시피를 관리해 주거나, 장비의 효율성을 높여주는 그런 이큅먼트 엔지니어링 솔루션을 제공해 왔습니다. 특히 초기에 집중했던 대표적인 분야는 FDC(Fault Detection and Classification)였습니다.”\n- FDC는 뭔가요?\n“쉽게 말하면, 공정이나 장비에 이상이 있는지를 감지하고 분류해주는 시스템입니다. 현재는 반도체나 디스플레이 분야에서 아주 핵심적인 시스템으로 자리 잡았고, 이상을 모니터링하고 공정이나 장비의 문제를 빠르게 감지하는 데 기본적으로 활용되고 있습니다.”\n- 라인 안에 장비가 상당히 많이 배치되어 있는데, 장비별로 다 비스텔 솔루션이 심어져 있는 건가요?\n“FDC는 어떻게 보면 중앙 시스템이라고 볼 수 있고요. 장비에서 발생하는 데이터들이 SECS(SEMI Equipment Communications Standard)나 GEM(Generic Equipment Model) 같은 표준 프로토콜을 통해서 호스트로 올라오면, 그 데이터를 실시간으로 처리하고, 모니터링하고, 비주얼라이제이션(시각화)까지 해주는 역할을 합니다. 여기에서 더 나아가 수율이나 품질 관련된 데이터들을 같이 분석해주는 방향으로 발전해 나가는 과정이었습니다.”\n- 어떤 회사들이 그 솔루션을 사용했습니까?\n“한국의 메이저 반도체, 디스플레이 회사들이 사용했고, 미국과 중국, 대만 등지에 다양한 고객군을 확보하고 있었습니다.”\n- 그런 솔루션이 한 회사에 구축되면 다른 회사 솔루션을 같이 쓰지는 않죠?\n“그렇죠. 보통 어떤 라인에 한 번 저희 시스템이 도입되면, 계속 확장해 나가는 형태로 사용하는 고객들이 많습니다. 물론 일부 특별한 경우에는 라인별로 개별 솔루션을 선택해서 적용하는 곳도 있지만, 대부분의 경우 저희 시스템이 회사의 표준 시스템으로 자리 잡아서, 그동안 큰 기여를 해왔다고 자부하고 있습니다.”\n- 그러면 SI 성격의 작업이었는지, 독자적인 솔루션인지 궁금합니다.\n“저희의 독자적인 솔루션이 기본적으로 들어가고 나면, 그다음에는 장비별로 모델링을 해주는 서비스가 필요합니다. 장비마다 올라오는 데이터가 다르거나, 스펙이 다르거나, 프로세스가 진행되는 스텝 구간들이 각각 다를 경우에 이에 대한 전문 서비스가 필요하기도 합니다.”\n- 시놉시스의 경우에 그렇게 쌓아져 있는 데이터를 활용해서 뭔가 다른 큰 사업을 진행하기 위해서 비스텔을 인수한 것이고, 비스텔리젼스는 기존에 공급했던 솔루션의 유지보수 위주로 사업을 하시는 건가요?\n“아닙니다. 기본적으로 서비스는 저희가 전담하기로 시놉시스와 계약되어 있어서 계속 서비스를 제공하고 있는 거고요. 그 외에, 앞서 말씀드렸듯이 후공정이나 퍼실리티 · 유틸리티 쪽에서 지능화할 수 있는 솔루션들을 개발해서 제공하고 있습니다.\n후공정 같은 경우, 전공정에서 사용하는 FDC를 사용하고는 있지만, 장비에서 제공되는 데이터가 굉장히 제한적이기 때문에, 저희는 엣지 플랫폼 기술을 활용해서 직접 장비에서 초고속, 대용량 데이터를 수집한 뒤, FDC와 같이 폴트 디텍션을 해주는 솔루션을 개발해서 현재 국내 오사트(OSAT ; Outsourced Semiconductor Assembly and Test) 업체와 함께 진행하고 있습니다.\n또 하나는, 저희 미국의 연구개발 법인, ‘아이덴틱스(Identix)’라는 자매 회사가 있는데, 거기서 나온 퍼포먼스 매니지먼트 시스템이라는 AI 기반 솔루션이 있습니다. 이 솔루션은 장비의 건강 상태와 효율을 모니터링하고 이상을 감지하는 시스템인데요. 이를 활용해서 현재 펌프나 칠러 같은, 팹(Fab) 내에서도 눈에 잘 띄지 않는 영역들의 자동화 수준을 높일 수 있는 솔루션도 함께 공급하고 있습니다.”\n- 그러면 전공정 분야에는 서비스 말고는 진행 중인 사업이 없습니까?\n“일단 저희가 하고 있는 APM, 즉 에셋 퍼포먼스 매니지먼트 시스템(Asset Performance Management System) 같은 경우는, 예지 보전이나 장비의 건강도 및 효율성을 높여주는 솔루션인데요. 이 부분은 시놉시스와 경쟁 관계가 아니기 때문에, 저희가 전공정 쪽에서도 직접 시도를 하고 있고, 또 PoC(개념검증)도 진행해서 굉장히 좋은 결과를 내고 있습니다.”\n- 그 솔루션은 어떤 그 원리로 작동되는 건가요?\n“장비에서 올라오는 데이터를 저희가 비지도 학습 기반의 AI 알고리즘을 활용해서 분석합니다. 처음 시스템을 적용했을 때의 상태를 정상 상태로 설정해 두고, 이후 변동 상황을 계속 추적하면 모델이 자동으로 업그레이드되면서 이상을 감지해 주는 방식입니다.\n궁극적으로는 장비의 잔여 수명을 예측해 주고, 예지 보전 단계까지 갈 수 있는 그런 솔루션을 제공하고 있고요. 또, 이런 기술을 기반으로 팹 내에서 장비 유지보수를 위한 활동까지 자동화할 수 있도록 지원하는 체계를 만들어주는 솔루션들을 지속적으로 개발하고 있습니다.”\n- 예전에 매각했던 사업 영업으로는 다시 진출할 수 없도록 계약이 되어 있는 건가요?\n“할 수 없다기보다는, 그 시장은 이미 굉장히 성숙한 시장이고, 경쟁이 쉽지 않은 굳어진 시장이기 때문에, 저희는 그보다는 니치(Niche) 영영이나 발전 가능성이 더 큰 영역들, 예를 들어 후공정이라든가, 요즘 많이 주목받고 있는 어드밴스드 패키징 같은 분야에서 기회를 만들기 위해 지속적으로 연구하고 있습니다.\n또 하나는, 요즘 AI, 특히 생성형 AI나 LLM(대규모 언어 모델)이 화두가 되고 있지 않습니까? 저희가 계속 주목하고 있는 부분은, 그동안 자동화라고 하면 주로 작업 현장에서의 단순 반복 작업을 자동화하는 것이 중심이었다면, 이제는 프로세스 협업(Collaboration)이나 워크플로우 자동화, 엔지니어 업무 자동화 같은 더 큰 방향으로 가고 있습니다. 그래서 저희는 앞서 말씀드렸던 R&D 법인과 함께 스몰 LLM을 만들어서 현장에서 어떻게 활용할 수 있을지 연구하고 있습니다.\n또, AI 에이전트라든가, 가트너(Gartner)에서 얘기하는 하이퍼오토메이션(Hyperautomation) 같은 개념과 맞물려, 보다 가치 있는 일을 할 수 있는 방향을 고민하고 있습니다. 이런 사업들은 사실 굉장히 장기적인 관점에서 고객과 함께 호흡을 맞춰가면서 진행해야 하는 일이라고 보고 있습니다. 저희가 지난 20여 년간 고객과 쌓아온 신뢰 관계를 바탕으로, 결국은 최근 화두가 되고 있는 오토노머스 매뉴팩처링(Autonomous Manufacturing)으로 나아갈 수 있는 기반을 함께 만들어보자는 방향으로, 계속 사업 기회를 모색해 나가고 있습니다.”\n- 그게 회사에서 얘기하는 코스모스 플랫폼이라는 것인가요?\n“예, 맞습니다. 코스모스 플랫폼에 LLM 그리고 엣지 플랫폼까지 결합해서 풀스택으로 데이터를 수집하고, 전처리해서 가치를 높여주는 작업, 또 그 데이터를 통해 인사이트를 찾아내는 작업, 결국은 전체적인 인텔리전스 수준을 높여주는 방향으로 가고 있습니다.\n저희는 이것을 데이터 옵스(DataOps)라고 명명했고요, 그런 풀스택을 갖춘 회사로 모습을 갖춰가기 위해, 최근에 데이터 분석 전문 역량을 갖고 계신 분들을 새로 모셨습니다. 또 한 축에서는, 그렇게 모은 데이터들을 제대로 활용하기 위해 퓨처 엔지니어링이라는 영역에서 솔루션 도구를 제공하는 제품화 작업도 현재 계속 진행하고 있습니다.”\n- 최근에 지어지는 반도체 팹의 전공정 공장은 IT 역량이 많이 녹아 있어서 거의 무인화가 되어 있더라고요. 앞서 성숙된 시장이라고 하셨는데 그럼에도 AI 같은 새로운 기술이 들어가 여지가 있지 않습니까?\n“사실 앞에서 말씀드렸던 FDC나 기존의 레거시 시스템들이 이제는 현장에서 굉장히 단단하게 자리를 잡았거든요. 이런 것들을 바꾸거나 새롭게 대체하는 것도 필요하긴 하지만, 현실적으로는 기존 시스템들을 손대기가 굉장히 쉽지 않은 상황이 됐습니다.\n그렇다면, 기존 시스템들을 어그멘테이션(Augmentation)해서 더 잘 활용할 수 있게 하거나, 아니면 인테그레이션(Integration)해서, 엔지니어들이 어떤 문제를 처리할 때 FDC도 보고, MES(Manufacturing Execution System)도 보고, 품질 시스템도 따로 보고 하는 이런 과정들을 자동화해 줄 수 있는 영역에서는 여전히 큰 시장이 있을 것으로 보고 있습니다.”\n- 그러면 MES, FDC 등등의 여러 시스템들을 다 통합한다는 말씀인가요?\n“통합이라기보다는, 각 시스템에서 필요한 데이터들을 한곳에 모아서 수집하고, 그 데이터들을 바탕으로 인사이트를 찾아내서 결국 의사결정이 가능하도록 해주는 부분,\n또는 더 나아가, 그런 데이터들을 기반으로 해서 필요한 액션까지 자동으로 실행해주는 부분에서 새로운 길이 있을 것으로 생각하고 있습니다.”\n- 궁금한 것이 있는데요, 대기업들은 SI 관련 계열사들이 다 있어서 컨설팅도 받고 솔루션도 개발해서 공급하지 않습니까? 그러면 비스텔리젼스는 그런 대기업 SI 업체와 경쟁하는 관계인가요, 아니면 협업을 하는 건가요?\n“다양한 가능성을 열어두고 보고 있습니다. 컨설팅 회사가 앞단에서 PI(Process Innovation) 를 하고 저희가 실제 딜리버리를 맡는 경우도 있고, 고객사와 직접 협업하는 경우도 많습니다. 저희는 현장에서 쌓아온 노하우나 실제 딜리버리 과정에서 경험했던 개선 포인트들을 누구보다 잘 알고 있다고 자부하고 있거든요. 그런 부분은 저희만큼 계열사 SI 업체나 다른 시스템 통합 회사들이 잘 알기는 어렵다고 생각합니다.\n그래서 저희는 그런 특화된 역량, 그리고 앞서 말씀드렸던 데이터 수집부터 활용까지의 경험과 기술력을 바탕으로, 고객의 가치를 높이는 방향에서 최대한 활용하려고 하고 있습니다. 저희는 경쟁도 하지만, 협업도 중요하게 생각하면서 그런 포지션을 잡으려고 하고 있습니다.\n최근에 저희가 많이 이야기하는 부분 중 하나가 서비스 애즈 솔루션(Service as a Solution) 인데요. 일반적으로 많이 아시는 SaaS(Software as a Service)와는 조금 다른 개념입니다. 저희는 고객 맞춤형 서비스를 제공해서, 고객에게 가치 있는 솔루션을 만들어 드리는 솔루션 중심의 서비스 모델을 전략적으로 가져가고 있습니다.”\n- 2024년 매출은 아직 발표하지 않으신 것 같은데, 2023년에는 100~150억 원 정도 하셨더라고요. 지금 추진하는 플랫폼 사업은 이제 시작 단계인가요?\n“지금은 시작 단계고, 저희도 서브스크립션(Subscription ; 구독) 모델로 비즈니스 형태를 전환해 나가고 있는 상황입니다. 요즘 구동(Perpetual) 라이선스에서 서브스크립션으로 전환할 때, 사실 매출이 갑자기 확 줄어드는 것처럼 보이는 경우가 있거든요. 물론 몇 년의 장기적인 관점에서 보면, 제로 베이스에서 시작하지 않아도 되는 안정적으로 좋은 사업 모델일 수 있지만, 아직은 서브스크립션 모델이 특히 한국 제조업 시장에서는 쉽게 받아들여지지 않는 측면도 있어서 어려움이 있기는 합니다.”\n- 구독 모델은 어떤 방식으로 하는 건가요?\n“솔루션마다 약간씩 다르긴 하지만, 장비당 과금할 수도 있고요. 또, 장비당 과금하는 경우라도 어떤 장비는 수천 개의 센서 데이터가 나오지만, 어떤 장비는 10개, 20개 정도로 적은 경우도 있기 때문에, 그런 부분에 대해서는 저희가 유연성을 가지고 접근하고 있습니다.”\n- 코스모스 플랫폼은 사겠다고 하는 회사가 있습니까?\n“있습니다. 디텍터 같은 솔루션은 플랫폼을 기반으로 해서 만든 것이라 플랫폼과 솔루션이 같이 들어갈 때 비용을 받는 사업 모델이 있고요. 또, 엣지 플랫폼 같은 경우는 저희가 파트너사와 같이 하면서 장비 대수 기준으로 과금하는 비즈니스 모델도 있습니다.”\n- 말씀하신 플랫폼에 대한 니즈가 실제로 많이 있습니까?\n“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사실 그렇게 크게 어필이 안 될 수도 있습니다. 그런데 저희가 다른 산업들을 경험해보면, 씨레벨(C-level) 분들은 ‘우리도 스마트 팩토리 해야지, AI, LLM 써서 뭔가 해야지’ 이런 말씀들을 많이 하시는데, 막상 현장에 가보면 상황이 정말 열악한 경우가 많습니다. 데이터가 아예 없는 곳들도 굉장히 많아요. 그런 현장에서는 아예 밑단부터 접근해서 풀어나가지 않으면 안 됩니다. 저희가 그런 부분을 안 하고 있으면, 결국 다른 업체가 들어와서 이쪽은 누가 하고, 저쪽은 또 다른 데가 하고, 이렇게 복잡한 관계가 생기기 때문에, 처음부터 저희가 직접 접근해서 해결해나가는 것이 중요하다고 보고 있습니다.”\n- 타깃으로 보는 기업들이 제조업일 텐데요, 매출 수준이 상당히 되는 기업들 아닌가요?\n“조 단위의 매출을 올리는 중견기업인데도 데이터가 전혀 나오지 않는 기업들이 많습니다. 그래서 저희 회사 나름의 자부심이 있다면, 제조업 전체의 수준을 향상시킬 수 있는 기반을 만들어 보는 것을 큰 미션 중 하나로 보고 있습니다.”\n- 반도체나 디스플레이 분야를 적극적으로 공략하지만, 이외에 일반 산업 분야도 취급하겠다는 것이죠?\n“특히나 소부장 쪽, 그러니까 소재·부품·장비 분야에서도, 사실은 굉장히 중요한 부품이나 소재를 공급하는 회사임에도 불구하고, 여전히 열악한 경우가 많습니다.”\n- 그런데 못하고 있죠. 반도체 장비 같은 경우에는 세미 표준도 있고 여러 표준화된 데이터들이 있어서 잘 될 수 있겠지만, 일반 제조업 같은 경우에는 그런 표준 같은 것이 없지 않습니까?\n“PLC 인터페이스가 주로 많죠. 거기에도 일정한 표준이 있기는 하지만, PLC 공급 업체마다 서로 다른 특성이 있어서 어렵습니다. 그런 부분들을 지능적으로 맥락화(Contextualization)해 줄 수 있다는 것이 저희 엣지 플랫폼이 가지고 있는 특징 중 하나입니다.\n또, 반도체 후공정의 와이어 본더 같은 장비들은 기계적인 움직임이 굉장히 빠르거든요. 초당 수천 건, 많게는 수만 건의 데이터가 나오는데, 이걸 그대로 네트워크로 받게 되면, 네트워크 부하가 감당이 안 되는 상황이 발생합니다. 그래서 장비를 잘 아는 저희 엔지니어들이 장비에서 아날로그 데이터를 디지털 데이터로 변환해주는 작업을 해서 데이터를 확보하는 역량까지 보유하고 있습니다.\n앞서 말씀드렸듯이, 후공정에서 장비 업체가 제공하는 데이터만으로 운영하는 FDC와는 수준 차이가 큰 거죠. 그래서 저희는 그런 한계를 넘어서기 위해 새로운 방향을 개척해 나가고 있는 상황입니다.”\n- 말씀하신 하이퍼 오토메이션이라는 분야에서 소개할 만한 성공 사례가 있습니까?\n“국내 한 오사트 업체와 파트너십를 맺고, 앞에서 말씀드렸던 반도체 후공정에서 고속의 기계적 데이터를 활용해 FDC를 적용하는 케이스를 진행했습니다. 작년 말까지 기본적인 공정인 와이어 본더, 백그라인더, 다이 어태치 같은 부분에서 진행이 됐고요.\n이를 기반으로 루트 코즈 애널리시스(Root Cause Analysis), 즉 불량이 발생했을 때 그 원인이 어디에 있는지를 찾아주는 분석 시스템도 준비하고 있습니다. AI 알고리즘을 활용해, 그런 분석 체계를 구축하는 작업을 시작하려고 하고 있습니다.”\n- 현재는 문제가 생겼다는 것을 알려주는 정도입니까?\n“그렇습니다. 현재는 비주얼라이제이션을 해서 트렌드를 분석하거나 이상에 발생했을 때 알람을 주는 정도입니다.”\n- 그전에는 그런 게 없었나요?\n“후공정 쪽에서는 상대적으로 부족한 부분이 있었던 것이죠.”\n- 사람이 가서 봐야 했던 거군요?\n“기존에 간단한 시스템이 있었다고 해도, 디테일한 부분까지 볼 수는 없었습니다. 장비에서는 초당 2천 건, 3천 건, 많게는 1만 건 가까이 데이터가 발생하는데, 장비가 보내주는 데이터 주기가 1초에 한 번꼴이라면, 그 1초 동안에 일어난 변화를 알 수가 없는 거죠. 사실 그 사이에 문제가 발생하는 경우가 아주 많을 수 있습니다. 그래서 저희는 새로운 솔루션을 통해 품질 등 여러 부분에서 강화할 수 있는 시스템을 구축했고, 최근에 1차 적용을 성공적으로 마무리했습니다.”\n- 언제 시작하신 거예요?\n“1년 반쯤 전에 시작했지만, 사실 그 전부터 준비해 왔죠.”\n- 그런 솔루션을 도입해야겠다는 결정은 어떤 때 주로 하게 되는 것 같습니까? 고객에게 납품했다가 문제가 생겼는데 그 원인을 모르겠다고 할 때 많이 생각할 것 같긴 합니다.\n“그런 경우가 많습니다. 사실 반도체도 마찬가지인데, 출하된 이후에 문제가 발생해서 다시 들어왔을 때 원인 분석을 하는 것은 굉장히 어렵거든요. 그래서 최근에 저희가 오사트 업체에 1차 마무리 보고를 드릴 때, 그 자리에서 대표이사님께서 이런 말씀을 하셨습니다.\n‘이제는 이 시스템이 모든 것들의 기반이 돼야 하고, 더 나아가 플립칩이라든가, 어드밴스드 패키지까지도 적용돼야만 우리가 고객들에게 품질을 보장할 수 있다’고 하셨습니다.\n이번 성공 사례를 기반으로 현재는 대만의 ASE(Advanced Semiconductor Engineering, Inc.)라든가 이런 대형 오사트 업체들과도 계속 협의를 이어가고 있는 상황입니다.”\n- 그렇게 1년 반 작업하시면 매출은 얼마나 나오나요?\n“이번에는 고객과의 조인트 디벨롭 형태여서 매출을 말씀드리기가 곤란합니다.”\n- 공정도 다르고 라인의 흐름 같은 것도 다 다를 거라서 대부분 다 조인트 디벨롭 형태가 아닌가요?\n“엣지 단의 데이터는 약간씩 다를 수 있지만, 그걸 모니터링하는 체계나 분석하는 체계는 저희가 충분히 표준화할 수 있다고 보고 있습니다. 그래서 향후 저희 비즈니스 방향으로 봤을 때, 엣지 단에서는 서비스가 많이 들어가겠지만, 분석 체계 쪽은 라이선스 사업으로 전환해 나가려고 하고 있습니다.\n또, 오사트 쪽 패키징 분야에서 저희가 시장성을 높게 보는 이유는, 팹보다 장비 대수가 훨씬 많기 때문입니다. 그런 점에서 가능성을 매우 크게 보고 있고요. 앞서 말씀드렸던 퍼포먼스 매니지먼트 시스템 같은 경우는, 지금은 주로 유틸리티나 퍼실리티 설비 쪽을 대상으로 하고 있지만, 외국계 굴지의 펌프 회사에서도 스마트 펌프를 만드는 데 저희 솔루션을 쓰려고 논의 중입니다.\n또, 국내에서도 다양한 업체 및 고객들과 진행하고 있고, 현재 소부장 분야에서도 실제로 활용이 되고 있습니다.”\n- 수집된 데이터를 AI 모델을 통해 지능화하는 전략을 추진하겠다고 하셨는데 설명 좀 해주시죠.\n“저희는 비지도 학습(Unsupervised Learning) 방법을 쓰고 있는데, 그 이유가 최근 장비나 펌프 같은 것들이 사실 고장이 잘 나지 않거든요. 그런데 지도 학습(Supervised Learning) 방식으로 접근하는 솔루션들은, 펌프가 다운된 이력들이 있어야 그걸 가지고 학습해서 적용하게 됩니다. 그러다 보니까 몇 년 치 데이터를 모아서 학습해야 하고, 그 과정이 굉장히 어렵고 복잡합니다.\n반면, 저희는 비지도 학습 방식을 활용해서, 처음부터 데이터를 정상 상태로 인식해 자동으로 모델링을 해주고, 이후 데이터 변화가 생기면 ‘이게 이상인가?’ 하고 감지해서 이벤트로 알려줍니다. 이런 이벤트가 몇 번만 맞아떨어지면, 모델이 점점 최적화되는 방식입니다.\n사실 최근에 PDM(Predictive Maintenance) 같은 솔루션들이 확산되기 어려운 이유는, 설비가 다운될 때까지 그냥 쓰는 경우가 많고, 막상 다운된 이후에도 그 이력을 몇 차례 거쳐야만 학습이 되기 때문인 것 같습니다. 그런 어려움을 해결하기 위해, 저희는 저희 나름대로 새로운 방법으로 접근하고 있는 것이죠.”\n- 회사 안에 사업부는 어떻게 나뉘어 있습니까?\n“데이터 컨설팅 사업, 그리고 운영 및 SI 서비스 사업, 그 외에 솔루션을 기반으로 하는 사업, 이렇게 세 분야로 구분되어 있습니다.”\n- 매출 비중은 어떻게 됩니까?\n“아무래도 서비스 쪽이 큽니다. 예전 시놉시스의 솔루션을 사용하는 기존 고객들에 대한 서비스 부분을 담당하고 있는데요. 한국의 주요 대기업 반도체 회사나 디스플레이 회사에서 저희 서비스를 사용하고 있고, 저희가 그 부분을 계속 맡아서 진행하고 있습니다.”\n- 그 서비스는 언제까지 유지되는 사업인가요?\n“확정된 것은 아니지만, 그 솔루션을 사용하고 있는 고객이라면 앞으로도 지속적으로 저희가 서비스를 제공하는 형태가 될 거라고 보고 있습니다.”\n- 그러다가 고객이 솔루션을 교체하면 없어지겠군요?\n“그게 바꾸기가 쉽지 않습니다. 소스 코드에 대한 접근이나 시스템에 대한 이해 같은 부분에서, 다른 회사가 테이크오버(Take Over)하기는 쉽지 않고요, 또 그동안 저희가 제공해 왔던 서비스들의 연속성 측면에서도, 그렇게 단순하게 변경하기는 어려울 거로 생각합니다.”\n- 서비스 분야의 매출 비중은 얼마나 되나요?\n“50% 조금 넘는 정도입니다.”\n- 회사의 목표라든지, 비전은 어떻게 설정하고 계세요?\n“제가 고객분들과 개인적으로 얘기할 때, 가끔 ‘버추얼 엔지니어 10만 양성설’이라는 표현을 쓰곤 합니다. 무슨 얘기냐 하면, 사실 반도체 현장에서 작업자들은 자동화를 통해 근무 환경이 굉장히 좋아졌고 많은 부분에서 업무 효율성도 높아졌는데, 오히려 엔지니어들의 워크 앤 라이프 밸런스는 개선되기보다는 오히려 더 어려운 방향으로 가고 있는 것 같아요.”\n- 어떤 분야의 엔지니어를 말씀하시는 거죠?\n“반도체 장비 공정 엔지니어입니다. 그리고 또 하나, 이건 세계적인 추세라고 생각하는데요. 경험과 노하우를 갖고 있던 엔지니어들이 점점 줄어드는 현상이 계속 발생하고 있고, 경험이 있는 인력을 확보하는 것이 점점 어려워지고 있는 상황입니다.\n이런 환경에서 결국 우리가 나아가야 할 방향은 AI, LLM(대규모 언어 모델), 생성형 AI 등을 활용해서 엔지니어들의 업무를 덜어주고, 자동화하는 것이라고 생각합니다. 그래서 저희는 하이퍼오토메이션(Hyperautomation) 개념을 기반으로, 전반적인 프로세스를 다시 보고, 자동화를 점진적으로 도입하는 방향으로 나가고 있습니다. 이를 통해 엔지니어들이 더 빠르게 의사결정(Decision Making)을 할 수 있도록 지원하는 것이 목표입니다.\n제가 이번 CES에서 젠슨 황이 AI 에이전트(Agent AI)와 피지컬 AI(Physical AI)를 언급한 내용에 상당히 공감했는데요. 현재 AI는 버추얼 어시스턴트(Virtual Assistant) 역할을 하면서 보조적인 도움을 주는 수준이지만, 다음 단계에서는 버추얼 엔지니어(Virtual Engineer), 즉 AI 에이전트가 24시간 엔지니어들이 놓칠 수 있는 부분까지 빠짐없이 챙겨주는, 마치 우렁각시 같은 존재가 될 수 있다고 봅니다.\n그리고 여기에 로보틱 AI(Robotics AI), 피지컬 AI 등이 결합되었을 때, 결국 오토노머스 매뉴팩처링(Autonomous Manufacturing), 즉 진정한 무인 자동화 공정으로 나아갈 수 있다고 보고 있습니다. 저희는 이 과정에서 함께할 수 있도록, 필요한 준비와 역량을 확보해 나가고 있으며, 이에 맞춘 솔루션 개발도 지속적으로 진행하면서 미래를 준비하고 있습니다.”\n- 현재 회사에 자금 조달 수요는 좀 있습니까?\n“현재까지는 특별한 계획이 없습니다.”\n- 회사의 수익 상황은 어떻습니까?\n“지금은 앞서 말씀드렸듯이, 제품 개발이라든가 미래로 나아가기 위한 기반을 다지는 과정에 있고, 또 전반적인 경제 상황 등의 영향도 있어서 수익이 좋은 상황은 아닙니다. 하지만 올해부터 BEP(Break-Even Point) 달성을 시작으로, 점차 수익을 늘려가서, 2028년에는 좋은 결과를 만들어 상장할 수 있도록 준비할 계획입니다.”\n- 2028년이라는 상장 시기를 고려하시는 이유는 2028년 매출 목표가 있기 때문입니까? 얼마나 하시려는 계획입니까?\n“지금 정확히 말씀드리기는 어렵습니다만, 저희가 뭔가를 할 수 있는 수준, 그리고 저희가 생각하는 밸류에이션을 만들 수 있는 수준을 그때까지는 만들어야겠다고 생각하고 있습니다.”\n- 올해 손익분기점을 돌파하는 것이 목표라고 말씀하셨는데, 꼭 달성하시기를 바라겠습니다. 오늘 말씀 고맙습니다.\n\n\n\n대담 : 한주엽 전문기자\r\n정리 : 손영준 에디터\r\n촬영편집 : 신일범\xa0프로\xa0\n \n\n관련기사\n\n\'148% 성장세\' 씨이랩... 엔비디아 특수 누렸다\n\n\n\n\n\n\n\n\n신일범 프로\nilbeom@thelec.kr\n\n\n다른기사 보기\n\n키워드\n#나인테크\n#김성수\n#배터리\n#반도체\n#후공정\n#유리기판\n#디스플레이\n#스태킹\n\n저작권자 © 디일렉(THE ELEC) 무단전재 및 재배포, AI학습 및 활용 금지\n\n\n\n\n개의 댓글\n\n\n\n\n\n\n\n\n\n\n회원로그인\n로그인 후 이용 가능합니다.\n\n댓글 내용입력\n\n\n\n0 / 400\n등록\n\n\n\n\n\n\n\n댓글 정렬\n\n최신순\n추천순\n답글순\n\n\n BEST댓글\n\nBEST 댓글\r\n\t\t\t\t\t답글과 추천수를 합산하여 자동으로 노출됩니다.\r\n\t\t\t\t\t닫기\n\n\n\n\n\n\n\n\n\n더보기\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n댓글삭제\n\n\n\n\n\r\n\t\t\t\t삭제한 댓글은 다시 복구할 수 없습니다.\r\n\t\t\t\t그래도 삭제하시겠습니까?\r\n\t\t\t\n\n\n비밀번호\n\n\n\n\n\n\n\n\n\xa0삭제\n\n\n\n\n\n\n\n\n\n\n\n\n\n댓글수정\n\n\n\n\n\r\n\t\t\t\t댓글 수정은 작성 후 1분내에만 가능합니다.\r\n\t\t\t\n\n\n\n본문\n\n / 400\t\t\t\t\t\n\n\n\n\n\n\n\n\n\n비밀번호\n\n\n\n\n\n\n\n\n\n\xa0수정\n\n\n\n\n\n\n\n\n\n내 댓글 모음\n닫기\n\n\n\n\n\n\n\n\n\n\n많이 본 뉴스\n\n\n1\nSK하이닉스, 용인 첫 클린룸 두 달 앞당긴다\n\n\n\n\n\n2\n에코앤드림, 中 독점한 LFP \'전구체\' 국내 최초 생산\n\n\n\n\n\n3\n단독\xa0이재용 회장 또 일냈다… 삼성, 테슬라에 5G 모뎀 공급\n\n\n\n\n\n4\n에코프로, 中 독점 LFP 배터리 핵심소재 탈피 첫걸음\n\n\n\n\n\n5\n삼성전자 P5, 다음달 공사 재개\n\n\n\n\n\n6\n삼성 엑시노스 2600, 갤럭시S26 언팩 한달 앞두고 성능 8% 개선\n\n\n\n\n\n7\n美 ITC, 삼성전자·구글 D램 특허 침해 조사 착수\n\n\n\n\n\n8\n애플, 내년 더 얇은 \'아이폰 에어\' 출시 검토\n\n\n\n\n\n9\nTSMC, 2nm 양산 발표...삼성·인텔 고객사 확보 비상\n\n\n\n\n\n10\n한미반도체, HPSP 주식 전량 매도...2750억원 확보\n\n\n\n\n\n에디터 추천뉴스\n\n\n\n단독\xa0SK온-현대차, 전기차 차세대 냉각 기술 \'LSC\' 공동 개발\n\n\n\n애플, 내년 더 얇은 \'아이폰 에어\' 출시 검토\n\n\n\n에코앤드림, 中 독점한 LFP \'전구체\' 국내 최초 생산\n\n\n\nLCD 가격도 오른다...완제품까지 \'도미노 인상\' 불가피\n\n\n\n에코프로, 中 독점 LFP 배터리 핵심소재 탈피 첫걸음\n\n\n\n\n\n\n\n\n\n\n최신뉴스\n\n애플, AI 파운데이션 모델 학습 위해 구글 제미나이 활용\n\n\n삼성 갤S26플러스, 전작과 같은 6.66인치로 출시...이달 양산\n\n\n안기현 반도체협회 전무 "AI 칩 잘 설계해야 AI 시장 주도할 것"\n\n\nLG이노텍, 광주 차량 AP 모듈 공장 증축...1000억원 투자\n\n\n콩가텍, 점프텍의 18개 COM 제품군 통합 완료\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n매체소개\n기사제보\n광고문의\n이용약관\n개인정보처리방침\n청소년보호정책\n저작권보호정책\n이메일무단수집거부\n\n\n법인명: 주식회사 디일렉\n주소: 서울특별시 강남구 언주로 709, 13층(송암빌딩)\n대표전화: 02-2658-4707\n팩스: 02-2659-4707\n청소년보호책임자: 이수환\n\n제호: 디일렉(THE ELEC)\n등록번호: 서울 아 05435\n등록일: 2018-10-15\n최초발행일: 2018-10-15\n발행인: 한주엽\n편집인: 장지영\n\nCopyright by 디일렉(THE ELEC) All rights reserved.\n\n\n\n\n\n\n\n\n\n\n\n모바일버전\n\n\n\n\n\n디일렉(THE ELEC)\n\n\n\n\n\n전체기사\n\n\n최신뉴스\n\n\n\n전체\n\n\n동정\n\n\n전자엔지니어\n\n\n컨콜전문\n\n\n통신\n\n\n\n\n\n중국산업동향\n\n\n\n전체\n\n\n반도체\n\n\n디스플레이\n\n\n배터리ㆍ소재부품\n\n\nIT 일반 기타\n\n\n\n\n\n반도체\n\n\n디스플레이\n\n\n배터리\n\n\n소재장비\n\n\n방산‧에너지\n\n\n완성품\n\n\n금융\n\n\nIT‧게임\n\n\n\n전체\n\n\n통신\n\n\n\n\n\nY인사이트\n\n\n오피니언\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')

In [20]:
def extract_longest_text(text):
    segments = text.split('\n')
    longest_segment = max(segments, key=len)
    
    return longest_segment

text = docs[0].page_content

longest_text = extract_longest_text(text)
print("가장 긴 텍스트:\n", longest_text)

가장 긴 텍스트:
 “반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사실 그렇게 크게 어필이 안 될 수도 있습니다. 그런데 저희가 다른 산업들을 경험해보면, 씨레벨(C-level) 분들은 ‘우리도 스마트 팩토리 해야지, AI, LLM 써서 뭔가 해야지’ 이런 말씀들을 많이 하시는데, 막상 현장에 가보면 상황이 정말 열악한 경우가 많습니다. 데이터가 아예 없는 곳들도 굉장히 많아요. 그런 현장에서는 아예 밑단부터 접근해서 풀어나가지 않으면 안 됩니다. 저희가 그런 부분을 안 하고 있으면, 결국 다른 업체가 들어와서 이쪽은 누가 하고, 저쪽은 또 다른 데가 하고, 이렇게 복잡한 관계가 생기기 때문에, 처음부터 저희가 직접 접근해서 해결해나가는 것이 중요하다고 보고 있습니다.”

In [21]:
from tqdm import tqdm
import time 

new_results = []
for result in tqdm(results):
    try:
        url = result['link']
        loader = WebBaseLoader(url)
        docs = loader.load()
        text = docs[0].page_content
        longest_Text = extract_longest_text(text)
        result['content']= longest_text
        new_results.append(result)
    except:
        pass

print("새로운 결과 개수 : ", len(new_results))
new_results[0]

100%|██████████| 20/20 [00:04<00:00,  4.74it/s]

새로운 결과 개수 :  20

{'position': 1,
 'title': '[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다',
 'source': {'name': '디일렉',
  'icon': 'https://encrypted-tbn3.gstatic.com/faviconV2?url=https://www.thelec.kr&client=NEWS_360&size=96&type=FAVICON&fallback_opts=TYPE,SIZE,URL'},
 'link': 'https://www.thelec.kr/news/articleView.html?idxno=33104',
 'thumbnail': 'https://cdn.thelec.kr/news/photo/202502/33104_31164_1118.jpg',
 'thumbnail_small': 'https://news.google.com/api/attachments/CC8iK0NnNTRWMFprUVdwVFNsbHdURkJsVFJDcUJCaXFCQ2dLTWdheFk1WlFLUWc',
 'date': '02/19/2025, 08:00 AM, +0000 UTC',
 'iso_date': '2025-02-19T08:00:00Z',
 'content': '“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사실 그렇게 크게 어필이 안 될 수도 있습니다. 그런데 저희가 다른 산업들을 경험해보면, 씨레벨(C-level) 분들은 ‘우리도 스마트 팩토리 해야지, AI, LLM 써서 뭔가 해야지’ 이런 말씀들을 많이 하시는데, 막상 현장에 가보면 상황이 정말 열악한 경우가 많습니다. 데이터가 아예 없는 곳들도 굉장히 많아요. 그런 현장에서는 아예 밑단부터 접근해서 풀어나가지 않으면 안 됩니다. 저희가 그런 부분을 안 하고 있으면, 결국 다른 업체가 들어와서 이쪽은 누가 하고, 저쪽은 또 다른 데가 하고, 이렇게 복잡한 관계가 생기기 때문에, 처음부터 저희가 직접 접근해서 해결해나가는 것이 중요하다고 보고 있습니다.”'}

In [22]:
import pandas as pd
data=pd.DataFrame(new_results)
data.head()

,position,title,source,link,thumbnail,thumbnail_small,date,iso_date,content
0,1,"[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다","{'name': '디일렉', 'icon': 'https://encrypted-tbn...",https://www.thelec.kr/news/articleView.html?id...,https://cdn.thelec.kr/news/photo/202502/33104_...,https://news.google.com/api/attachments/CC8iK0...,"02/19/2025, 08:00 AM, +0000 UTC",2025-02-19T08:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사..."
1,2,"비스텔리젼스, '제조 AI' 전용 데이터 가공 솔루션 출시","{'name': '디일렉', 'icon': 'https://encrypted-tbn...",https://www.thelec.kr/news/articleView.html?id...,https://cdn.thelec.kr/news/photo/202502/32943_...,https://news.google.com/api/attachments/CC8iK0...,"02/13/2025, 08:00 AM, +0000 UTC",2025-02-13T08:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사..."
2,3,이한주 비스텔리젼스 대표 “'비스텔리젼스 에지 IoT 플랫폼'으로 산업계 DX 뒷받침”,"{'name': '전자신문', 'icon': 'https://encrypted-tb...",https://www.etnews.com/20230317000043,https://img.etnews.com/photonews/2303/1631577_...,https://news.google.com/api/attachments/CC8iK0...,"03/17/2023, 07:00 AM, +0000 UTC",2023-03-17T07:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사..."
3,4,"[신년사] 비스텔리젼스 ""산업 데이터분석 신규 솔루션 선보인다""","{'name': 'AI타임스', 'icon': 'https://encrypted-t...",https://www.aitimes.com/news/articleView.html?...,https://cdn.aitimes.com/news/photo/202402/1569...,https://news.google.com/api/attachments/CC8iK0...,"02/02/2024, 08:00 AM, +0000 UTC",2024-02-02T08:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사..."
4,5,한국 제조AI의 개척자 “테크 유행어에 겁먹지 말라”,"{'name': '포춘코리아 디지털 뉴스', 'icon': 'https://encr...",https://www.fortunekorea.co.kr/news/articleVie...,https://www.fortunekorea.co.kr/news/photo/2023...,https://news.google.com/api/attachments/CC8iK0...,"06/25/2023, 07:00 AM, +0000 UTC",2023-06-25T07:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사..."

## 뉴스 요약

In [23]:
from langchain_core.prompts import PromptTemplate
from langchain_ollama import OllamaLLM

from langchain_core.output_parsers import StrOutputParser

#promopt
prompt_template = """다음 내용을 한국어(한글)로 간결하게 요약하라.

규칙:
- 요약 내용만 출력한다
- 영어 문장, 설명, 인사말을 포함하지 않는다
- 불필요한 문구 없이 바로 요약문만 작성한다

내용:
{text}
"""
prompt = PromptTemplate.from_template(prompt_template)

#LLM
llm = OllamaLLM(model="gemma3:12b")

#parser
output_parser = StrOutputParser()

llm_chain = prompt | llm | output_parser

response = llm_chain.invoke({"text": data['content'][0]})

response

'고성능 기술 분야에서는 스마트 팩토리나 AI 도입에 대한 요구가 많지만, 현장 데이터 부재 등 열악한 환경이 많다. 따라서 기본부터 직접 접근하여 문제를 해결하는 것이 중요하며, 그렇지 않으면 여러 업체가 개입하여 복잡한 상황이 발생할 수 있다.\n'

In [24]:
def summarize_news(content):
    response = llm_chain.invoke({"text": content})
    return response

df_test = data.head(3)
df_test['summary'] = df_test['content'].apply(summarize_news)

df_test

C:\Users\Bistelligence\AppData\Local\Temp\ipykernel_31272\2177543294.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['summary'] = df_test['content'].apply(summarize_news)

,position,title,source,link,thumbnail,thumbnail_small,date,iso_date,content,summary
0,1,"[Y인사이트] 비스텔리젼스, 반도체 자동화와 AI로 새 길을 연다","{'name': '디일렉', 'icon': 'https://encrypted-tbn...",https://www.thelec.kr/news/articleView.html?id...,https://cdn.thelec.kr/news/photo/202502/33104_...,https://news.google.com/api/attachments/CC8iK0...,"02/19/2025, 08:00 AM, +0000 UTC",2025-02-19T08:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 어필이 어렵고, 기업들이 스마트 팩토리 도입을 원하..."
1,2,"비스텔리젼스, '제조 AI' 전용 데이터 가공 솔루션 출시","{'name': '디일렉', 'icon': 'https://encrypted-tbn...",https://www.thelec.kr/news/articleView.html?id...,https://cdn.thelec.kr/news/photo/202502/32943_...,https://news.google.com/api/attachments/CC8iK0...,"02/13/2025, 08:00 AM, +0000 UTC",2025-02-13T08:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 성과를 내기 어렵고, 많은 기업들이 스마트 팩토리 ..."
2,3,이한주 비스텔리젼스 대표 “'비스텔리젼스 에지 IoT 플랫폼'으로 산업계 DX 뒷받침”,"{'name': '전자신문', 'icon': 'https://encrypted-tb...",https://www.etnews.com/20230317000043,https://img.etnews.com/photonews/2303/1631577_...,https://news.google.com/api/attachments/CC8iK0...,"03/17/2023, 07:00 AM, +0000 UTC",2023-03-17T07:00:00Z,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","스마트 팩토리 및 AI 도입을 희망하는 기업들이 많지만, 현장 데이터 부족 등 열악..."

In [25]:
df_test[['content', 'summary']]

,content,summary
0,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 어필이 어렵고, 기업들이 스마트 팩토리 도입을 원하..."
1,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 성과를 내기 어렵고, 많은 기업들이 스마트 팩토리 ..."
2,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","스마트 팩토리 및 AI 도입을 희망하는 기업들이 많지만, 현장 데이터 부족 등 열악..."

## 키워드 추출

In [26]:
from langchain_core.prompts import PromptTemplate
from langchain_ollama import OllamaLLM
from langchain_core.output_parsers import StrOutputParser

#prompt
prompt_template = """Please extract 3 key words form the following content in Korean Hangul(한글) and separate them with commas (,) 
"{text}" 
Key words :"""

prompt = PromptTemplate.from_template(prompt_template)

#LLM 
llm = OllamaLLM(temperature = 0, model="gemma3:12b")

#ouput parser
output_parser = StrOutputParser()

#Chain
llm_chain = prompt | llm | output_parser

response = llm_chain.invoke({"text": data['content'][0]})

response

'Here are 3 keywords extracted from the Korean text, separated by commas:\n\n스마트 팩토리, AI, 데이터\n'

In [27]:
# 뉴스 본문을 입력으로 사용하여 핵심 키워드를 추출하는 함수 
def extract_keywords(content):
    response = llm_chain.invoke({"text": content})
    return response

#결과 확인 - 테스트를 위해서 첫 3행만 별도로 추출하여 추출 
df_test['keywords'] = df_test['content'].apply(extract_keywords)

df_test[['content', 'summary' , 'keywords']]

C:\Users\Bistelligence\AppData\Local\Temp\ipykernel_31272\1007077600.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['keywords'] = df_test['content'].apply(extract_keywords)

,content,summary,keywords
0,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 어필이 어렵고, 기업들이 스마트 팩토리 도입을 원하...",Here are 3 keywords extracted from the Korean ...
1,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 성과를 내기 어렵고, 많은 기업들이 스마트 팩토리 ...",Here are 3 keywords extracted from the Korean ...
2,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","스마트 팩토리 및 AI 도입을 희망하는 기업들이 많지만, 현장 데이터 부족 등 열악...",Here are 3 keywords extracted from the Korean ...

## 뉴스 카테고리 분류

In [28]:
from langchain_core.prompts import PromptTemplate
from langchain_ollama import OllamaLLM
from langchain_core.output_parsers import StrOutputParser 

#prompt 
prompt_template = """Based on the following content, please classify the news into the approproiate category and provide the category name in Korean without description:
"{text}"
News Category:"""

prompt = PromptTemplate.from_template(prompt_template)

#LLM 
llm = OllamaLLM(temperature = 0, model="gemma3:12b")

#output parser
output_parser = StrOutputParser()

#chain
llm_chain = prompt | llm | output_parser

response = llm_chain.invoke({"text": data['content'][0]})

response

'산업 동향 (産業動向)'

In [29]:
#뉴스 본문을 입력으로 사용하여 카테고리를 분류하는 함수 
def classify_news_category(content):
    response = llm_chain.invoke({"text": content})
    return response

#결과 확인 - 테스트를 우해서 첫 3행만 별도로 추출하여 카테고리 분류 
df_test['category'] = df_test['content'].apply(classify_news_category)

df_test[['content', 'summary', 'keywords', 'category']]

C:\Users\Bistelligence\AppData\Local\Temp\ipykernel_31272\997070006.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['category'] = df_test['content'].apply(classify_news_category)

,content,summary,keywords,category
0,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 어필이 어렵고, 기업들이 스마트 팩토리 도입을 원하...",Here are 3 keywords extracted from the Korean ...,산업 동향 (産業動向)
1,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","하이테크 산업에서는 표준화로 큰 성과를 내기 어렵고, 많은 기업들이 스마트 팩토리 ...",Here are 3 keywords extracted from the Korean ...,산업 동향 (産業動向)
2,"“반도체나 디스플레이처럼 하이테크 산업군이면서 표준화가 잘 돼 있는 분야에서는, 사...","스마트 팩토리 및 AI 도입을 희망하는 기업들이 많지만, 현장 데이터 부족 등 열악...",Here are 3 keywords extracted from the Korean ...,산업 동향 (産業動向)